name: check label of PR to main

on:
  pull_request:
    branches:
      - main
    types:
      - synchronize
      - labeled
      - unlabeled
      - opened
      - reopened

jobs:
  check_label:
    if: github.base_ref == 'main'
    runs-on: [ self-hosted ]
    permissions:
      contents: write
      pull-requests: write
    timeout-minutes: 10
    env:
      MASTER_BRANCH: main

    steps:
      - uses: actions/checkout@v3

      - name: Debugging - Print GitHub Event Details
        run: |
          echo "GitHub Event: ${{ toJson(github.event) }}"
          echo "Repository: ${{ github.repository }}"
          echo "PR Number: ${{ github.event.number }}"

      - name: gh auth login
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh auth login --with-token

      - name: check label of PR to main
        continue-on-error: false
        env:
          TZ: "Asia/Tokyo"
        run: |
          i=0
          
          # PRのラベル情報を取得
          echo "Fetching labels for PR #${{ github.event.number }} in repository ${{ github.repository }}"
          items=$(gh pr view ${{ github.event.number }} --repo "${{ github.repository }}" --json labels -q '.labels')
          
          # デバッグ用：取得したラベルのJSONを表示
          echo "Labels JSON: $items"

          # IFSを改行に設定してラベルをループ処理
          IFS=$'\n'
          for item in $(echo "$items" | jq -r '.[].name'); do
              echo "Label found: $item"
              case "${item}" in
                  "major"|"minor"|"patch")
                      ((i++))
                      ;;
              esac
          done

          # ラベルの数をチェック
          if [ $i -eq 0 ]; then
              echo "エラー: 更新するリリースバージョンのlabelを付けてください (major, minor, patch のいずれか)"
              exit 1
          fi
          if [ $i -gt 1 ]; then
              echo "エラー: リリースバージョンのlabelを2つ以上つけないでください"
              exit 1
          fi

          echo "チェック完了: 適切なラベルが1つ設定されています。"

      - name: gh auth logout
        run: gh auth logout
