      - name: check label of PR to main
        continue-on-error: false
        run: |
          set -x  # ← 追加（デバッグ用）
          i=0
          
          # PRのラベル情報を取得
          echo "Fetching labels for PR #${{ github.event.number }} in repository ${{ github.repository }}"
          items=$(GH_TOKEN=${{ secrets.GITHUB_TOKEN }} gh pr view ${{ github.event.number }} --repo "${{ github.repository }}" --json labels -q '.labels')
          
          # デバッグ用：取得したラベルのJSONを表示
          echo "Labels JSON: $items"

          # IFSを改行に設定してラベルをループ処理
          IFS=$'\n'
          for item in $(echo "$items" | jq -r 'map(.name) | .[]'); do
              echo "Label found: $item"
              case "${item}" in
                  "major"|"minor"|"patch")
                      ((i++))
                      ;;
              esac
          done

          echo "Label count: $i"  # ← 追加（デバッグ用）

          # ラベルの数をチェック
          if [ $i -eq 0 ]; then
              echo "エラー: 更新するリリースバージョンのlabelを付けてください (major, minor, patch のいずれか)"
              exit 1
          fi
          if [ $i -gt 1 ]; then
              echo "エラー: リリースバージョンのlabelを2つ以上つけないでください"
              exit 1
          fi

          echo "チェック完了: 適切なラベルが1つ設定されています。"
